add view comic feature
chingu-voyages/v43-tier3-team-36 pull request #118
Opened 2023-04-04 16:26 UTC by fmtabbara

In the explore page a user can select a comic to view comic details AND see a list of users that have that comic in their collection.

2023-04-04 16:47 UTC, TazDeCoder approved these changes

2023-04-04 17:33 UTC, beblicarl approved these changes

2023-04-04 18:41 UTC, TazDeCoder requested changes
@fmtabbara after having a look at the components myself, I realized the **email of the user is exposed** which shouldn't be the case.

Can you please remove that because it should be the contact info supplied from the user - **remember**

If you wouldn't mind, can you add an extra field for the user called **contactInfo** which is basically a string that the frontend can use to display on a modal once the **'Contact'** button if you get the gist of what I'm saying here - if so, then please go ahead and do this

2023-04-08 16:47 UTC, TazDeCoder approved these changes

2023-04-08 16:49 UTC, TazDeCoder approved these changes
The frontend is fine 👍🏾

2023-04-18 15:51 UTC, merged