Feature/issue 20/user authentication
chingu-voyages/v43-tier3-team-36 pull request #64
Opened 2023-03-24 23:10 UTC by Pearlsky

This PR does the following

- [x] creates an app-wide alert component which can be extended; closes #63 

- [x] updates the code for the backend API response for a login req. @Danthesage01 

- [x] cleans up auth logic using react query and react-hook-form 

- [x] creates a zustand store for the User state and the Alert state

2023-03-25 14:01 UTC, TazDeCoder commented on packages/frontend/src/components/ui/Alert/Alert.tsx
Can you please remove this code a make a separate issue for this component - unit tests are missing

2023-03-25 14:31 UTC, TazDeCoder requested changes
There are a lot of changes to be made on the frontend before this PR can be merged.

Please read the comments I've made and feel free to ask me any other questions you may have.

Thanks

2023-03-25 14:31 UTC, TazDeCoder commented on packages/frontend/src/components/ui/Alert/Alert.tsx
Can you make a separate issue for this component - unit tests are missing for this

2023-03-25 14:31 UTC, TazDeCoder commented on packages/frontend/src/components/auth/FormField/FormField.tsx
Can you export this component as a default instead of a single export because we only need the component not the `FormFieldProps`

2023-03-25 14:31 UTC, TazDeCoder commented on packages/frontend/src/pages/_app.tsx
Can you please remove these changes because this will cause **unnecessary renders throughout the app** since pages will render at the **root level** instead of at **individual components**.

I advise to create a file called `Alert` in the `layouts` folder and import your `Alert` component from the `ui` folder so you use this new component that has the **logic encapsulated with the alert store** in all of the other layout files such as `Layout` and `AuthLayout` if you want this to act as a **global component** to solve this **re-rendering issue**

2023-03-25 14:31 UTC, TazDeCoder commented on packages/frontend/src/services/AuthService.ts
There's already an `api` folder which is supposed to store these services in the `src` directoy - can you kindly move the contents of this file into that folder and delete this file as well

2023-03-25 14:31 UTC, TazDeCoder commented on packages/frontend/src/store/store.ts
Can you make a separate issue for this store - the store for the user is already dealt by react-query, but the **alert** store I would like to know the purpose for this - we can discuss this in that separate issue

2023-03-25 14:31 UTC, TazDeCoder commented on packages/frontend/src/pages/login.tsx
Please redirect the user to the `profile` page route if the **login is successful**

2023-03-25 14:31 UTC, TazDeCoder commented on packages/frontend/src/pages/signup.tsx
Please redirect the user to the `profile` page route if the **signup is successful**

2023-03-25 15:47 UTC, Pearlsky commented on packages/frontend/src/components/ui/Alert/Alert.tsx
okay, noted

2023-03-25 16:18 UTC, Pearlsky commented on packages/frontend/src/pages/_app.tsx
I see what you're saying, okay

2023-03-25 19:50 UTC, Pearlsky commented on packages/frontend/src/services/AuthService.ts
I hadn't noticed the `api` folder, but i'd pull the dev branch to see what's up-to-date & make these changes

2023-03-25 22:20 UTC, Pearlsky commented on packages/frontend/src/pages/signup.tsx
done

2023-03-25 22:20 UTC, Pearlsky commented on packages/frontend/src/store/store.ts
done

2023-03-25 22:21 UTC, Pearlsky commented on packages/frontend/src/pages/signup.tsx
done

2023-03-25 22:21 UTC, Pearlsky commented on packages/frontend/src/pages/_app.tsx
can we talk more about this on the alert issue?

2023-03-26 05:35 UTC, Pearlsky commented
@TazDeCoder please review this again. some things are commented out until other prs are merged

2023-03-26 14:11 UTC, TazDeCoder approved these changes
Some considerations for refactoring, but these can be addressed easily

2023-03-26 14:11 UTC, merged